### ISSUE TITLE
Discord Server entirely unaccessible.

### ISSUE THREAD

**Issue by SephirothWS** [hylian-modding/ModLoader64#37]
As someone who does not have a valid cellular number that discord's discriminatory verification service accepts (They do NOT like prepaid, voip or landline numbers), I am unable to proceed to the welcome channel for the `?rank User` command. I would like assistance with this step since Discord prevents me from doing any sort of interaction with the server while this discriminatory requirement is active. One of two things should be done:
1. Remove the phone verification requirement from the server.
2. Manually grant me the user role.

I have attempted to send DMs asking for assistance, but these DMs are either blocked before they're sent, or entirely ignored.

**Comment by denoflionsx** [comment]
The phone verification stays on because it cuts down incoming spam bots from a dozen a day to one every few days.

I don't think you'll find many administrators of large discord servers that have their DMs open, so being unable to DM staff isn't unusual.

You didn't provide your Discord ID (username#discriminator or account id) without which I can't provide any assistance.

**Comment by SephirothWS** [comment]
My discord ID is Sephiroth#2168 .. I would greatly appreciate some assistance. Thank you @denoflionsx
